// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWRv11yUHUmzrFiwjqg20b-nJ1xC5naq4',
    appId: '1:738572341195:web:b204a1b68dbdd1dda0f04e',
    messagingSenderId: '738572341195',
    projectId: 'f-store-74d0e',
    authDomain: 'f-store-74d0e.firebaseapp.com',
    storageBucket: 'f-store-74d0e.appspot.com',
    measurementId: 'G-RN9D7K1CET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTf3iHNuJuCe4tiyWTAXEKNQwv-9oF44',
    appId: '1:738572341195:android:4136bbaf464e8af1a0f04e',
    messagingSenderId: '738572341195',
    projectId: 'f-store-74d0e',
    storageBucket: 'f-store-74d0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoeis0-8Y-74jva_tIGhdOZFo88EeKGak',
    appId: '1:738572341195:ios:589e26b845f29398a0f04e',
    messagingSenderId: '738572341195',
    projectId: 'f-store-74d0e',
    storageBucket: 'f-store-74d0e.appspot.com',
    androidClientId: '738572341195-at9s7bguob353ufur3j8h1glr7c0moii.apps.googleusercontent.com',
    iosClientId: '738572341195-5hb51mu6tmoejc1a6jkeciaskfbbouko.apps.googleusercontent.com',
    iosBundleId: 'com.example.fStore',
  );

}